### ISSUE TITLE
Support modals

### ISSUE THREAD

**Issue by HyperGH** [brazier-dev/hikari-flare#83]
```python
@dataclass
class TextInput:
    label: str
    placeholder: str


@dataclass_transform()
class Model:
    def add_field(self):
        ...


class Test(Model):
    a: int
    b: str

    input_one: TextInput = TextInput(label="1234", placeholder="1234")
    input_two: TextInput = TextInput(label="label 2", placeholder="placeholder 2")

    async def callback(self, ctx: flare.ModalContext):
        ...
```

**Comment by thesadru** [comment]
Would be cool if `TextInput` also had a way to store data with custom_id, not just the modal.

**Comment by Lunarmagpie** [comment]
I can't justify storing data on `TextInput`. Its way more complex than storing it on the modal for the end user anyway and adds a ton of complexity to the code. I prefer hyper's solution of using the extra space from the text input custom IDs to store more info which I think can be PRed after the modal PR.
